<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2024-04-24T16:51:29+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'OtakuSociety',
        ],
    ],
];
